### ISSUE TITLE
getting error:  ERROR:config.py:Unable to find section: mpulse

### ISSUE THREAD

**Issue by kmaqsudi** [akshayranganath/cli-mpulse#2]
./akamai-mpulse --api my-alphanumeric-api-key --timer=DomLoad
ERROR:config.py:Unable to find section: mpulse
ERROR:config.py:Unable to generate a token.

I have added my token to the ~/.mpulse file and ensured that i have python3

**Comment by tai** [comment]
I believe this issue is now gone (I'm now maintaining the package and re-checked the issue).
By default, mPulse CLI reads a token from ~/.mpulse file in following format:

```
[mpulse]
apiToken=your-api-token
tenant=your-tenant-name
```

Both configuration file and section can be switched with `--config` and `--section` options.

I'm now closing the issue as this ticket is outdated and all tests (which reads [mpulse] section in ~/.mpulse) did pass.
